### ISSUE TITLE
FR: ability to draw polygons (empty and/or filled) instead of single lines

### ISSUE THREAD

**Issue by tipiak75** [Jormund/automultidraw#2]
Would it be possible to draw polygons instead of single lines for UX sake ? In the current state, manual edition or deletion of the resulting draw outside of the bookmarks is a little painful, deleting a layer means deleting the two links drawn independently from each other. Drawing polygons instead of single lines would be a nice fix.

I also sometimes wish automultidraw would be able to draw filled polygons as autodraw currently does (visually more appealing, and it can even be useful UX-wise if the smaller polygons are stacked on top of bigger ones - otherwise you cannot select any small polygon, unless you delete first the top-level bigger ones - as we discussed).

**Comment by Jormund** [comment]
I've added 3 different draw modes.
It's in a branch for now:
https://raw.githubusercontent.com/Jormund/automultidraw/Issue%232/automultidraw.user.js
I think I need to make a separate window for preferences, to keep the display small.

**Comment by Jormund** [comment]
Pref window done.

**Comment by Jormund** [comment]
Merged with master on 03/08/2018
